services:
  - type: web
    name: jantama-records
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PGSSLMODE
        value: require
