--
-- PostgreSQL database dump
--


-- Dumped from database version 17.8 (a48d9ca)
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: characters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.characters (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    icon_filename character varying(100) DEFAULT NULL::character varying
);


--
-- Name: characters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.characters_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: characters_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.characters_id_seq OWNED BY public.characters.id;


--
-- Name: interviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interviews (
    id integer NOT NULL,
    tournament_id integer NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    question text NOT NULL,
    answer text DEFAULT ''::text NOT NULL
);


--
-- Name: interviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.players (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    nickname character varying(50) DEFAULT NULL::character varying,
    character_id integer,
    discord_user_id character varying(32),
    discord_username character varying(64)
);


CREATE UNIQUE INDEX IF NOT EXISTS idx_players_discord_user_id ON public.players (discord_user_id) WHERE discord_user_id IS NOT NULL;


--
-- Name: players_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.players_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: players_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.players_id_seq OWNED BY public.players.id;


--
-- Name: round_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.round_results (
    id integer NOT NULL,
    player_id integer NOT NULL,
    round_number integer NOT NULL,
    score numeric(10,1) NOT NULL,
    tournament_id integer NOT NULL,
    game_number integer DEFAULT 1 NOT NULL
);


--
-- Name: round_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.round_results_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: round_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.round_results_id_seq OWNED BY public.round_results.id;


--
-- Name: standings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.standings (
    player_id integer NOT NULL,
    rank integer NOT NULL,
    total numeric(10,1) DEFAULT 0 NOT NULL,
    pending boolean DEFAULT false,
    eliminated_round integer DEFAULT 0,
    tournament_id integer NOT NULL
);


--
-- Name: tournament_dm_dispatches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tournament_dm_dispatches (
    tournament_id integer NOT NULL,
    player_id integer NOT NULL,
    sent_at timestamp with time zone DEFAULT now() NOT NULL,
    status character varying(16) NOT NULL
);

ALTER TABLE ONLY public.tournament_dm_dispatches
    ADD CONSTRAINT tournament_dm_dispatches_pkey PRIMARY KEY (tournament_id, player_id);


--
-- Name: discord_scheduled_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discord_scheduled_events (
    entity_type character varying(16) NOT NULL,
    entity_id integer NOT NULL,
    discord_event_id character varying(32) NOT NULL,
    guild_id character varying(32) NOT NULL,
    last_synced_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.discord_scheduled_events
    ADD CONSTRAINT discord_scheduled_events_pkey PRIMARY KEY (entity_type, entity_id);


--
-- Name: table_paifu_urls; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.table_paifu_urls (
    id integer NOT NULL,
    table_id integer NOT NULL,
    game_number integer DEFAULT 1 NOT NULL,
    url text DEFAULT ''::text NOT NULL
);


--
-- Name: table_paifu_urls_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.table_paifu_urls_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: table_paifu_urls_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.table_paifu_urls_id_seq OWNED BY public.table_paifu_urls.id;


--
-- Name: table_players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.table_players (
    id integer NOT NULL,
    table_id integer NOT NULL,
    player_id integer NOT NULL,
    seat_order integer DEFAULT 0 NOT NULL
);


--
-- Name: table_players_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.table_players_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: table_players_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.table_players_id_seq OWNED BY public.table_players.id;


--
-- Name: tables_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tables_info (
    id integer NOT NULL,
    round_number integer NOT NULL,
    table_name character varying(20) NOT NULL,
    done boolean DEFAULT false,
    tournament_id integer NOT NULL,
    played_date date,
    day_of_week character varying(10) DEFAULT ''::character varying NOT NULL,
    played_time character varying(5) DEFAULT ''::character varying NOT NULL
);


--
-- Name: tables_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tables_info_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tables_info_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tables_info_id_seq OWNED BY public.tables_info.id;


--
-- Name: tournament_meta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tournament_meta (
    key character varying(50) NOT NULL,
    value character varying(200) NOT NULL,
    tournament_id integer NOT NULL
);


--
-- Name: tournaments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tournaments (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    status character varying(20) DEFAULT 'in_progress'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: tournaments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tournaments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tournaments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: characters id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.characters ALTER COLUMN id SET DEFAULT nextval('public.characters_id_seq'::regclass);


--
-- Name: players id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players ALTER COLUMN id SET DEFAULT nextval('public.players_id_seq'::regclass);


--
-- Name: round_results id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_results ALTER COLUMN id SET DEFAULT nextval('public.round_results_id_seq'::regclass);


--
-- Name: table_paifu_urls id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.table_paifu_urls ALTER COLUMN id SET DEFAULT nextval('public.table_paifu_urls_id_seq'::regclass);


--
-- Name: table_players id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.table_players ALTER COLUMN id SET DEFAULT nextval('public.table_players_id_seq'::regclass);


--
-- Name: tables_info id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tables_info ALTER COLUMN id SET DEFAULT nextval('public.tables_info_id_seq'::regclass);


--
-- Name: characters characters_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_name_key UNIQUE (name);


--
-- Name: characters characters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_pkey PRIMARY KEY (id);


--
-- Name: interviews interviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviews
    ADD CONSTRAINT interviews_pkey PRIMARY KEY (id);


--
-- Name: players players_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_name_key UNIQUE (name);


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);


--
-- Name: round_results round_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_results
    ADD CONSTRAINT round_results_pkey PRIMARY KEY (id);


--
-- Name: round_results round_results_unique_game; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_results
    ADD CONSTRAINT round_results_unique_game UNIQUE (tournament_id, player_id, round_number, game_number);


--
-- Name: standings standings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standings
    ADD CONSTRAINT standings_pkey PRIMARY KEY (tournament_id, player_id);


--
-- Name: table_paifu_urls table_paifu_urls_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.table_paifu_urls
    ADD CONSTRAINT table_paifu_urls_pkey PRIMARY KEY (id);


--
-- Name: table_paifu_urls table_paifu_urls_table_id_game_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.table_paifu_urls
    ADD CONSTRAINT table_paifu_urls_table_id_game_number_key UNIQUE (table_id, game_number);


--
-- Name: table_players table_players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.table_players
    ADD CONSTRAINT table_players_pkey PRIMARY KEY (id);


--
-- Name: tables_info tables_info_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tables_info
    ADD CONSTRAINT tables_info_pkey PRIMARY KEY (id);


--
-- Name: tournament_meta tournament_meta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tournament_meta
    ADD CONSTRAINT tournament_meta_pkey PRIMARY KEY (tournament_id, key);


--
-- Name: tournaments tournaments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tournaments
    ADD CONSTRAINT tournaments_pkey PRIMARY KEY (id);


--
-- Name: idx_table_players_table_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_table_players_table_id ON public.table_players USING btree (table_id);


--
-- Name: idx_tables_info_tournament_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tables_info_tournament_id ON public.tables_info USING btree (tournament_id);


--
-- Name: interviews_tournament_id_sort_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX interviews_tournament_id_sort_order ON public.interviews USING btree (tournament_id, sort_order);


--
-- Name: interviews interviews_tournament_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviews
    ADD CONSTRAINT interviews_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON DELETE CASCADE;


--
-- Name: players players_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.characters(id) ON DELETE SET NULL;


--
-- Name: round_results round_results_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_results
    ADD CONSTRAINT round_results_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE CASCADE;


--
-- Name: round_results round_results_tournament_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.round_results
    ADD CONSTRAINT round_results_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON DELETE CASCADE;


--
-- Name: standings standings_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standings
    ADD CONSTRAINT standings_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE CASCADE;


--
-- Name: standings standings_tournament_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standings
    ADD CONSTRAINT standings_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON DELETE CASCADE;


--
-- Name: table_paifu_urls table_paifu_urls_table_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.table_paifu_urls
    ADD CONSTRAINT table_paifu_urls_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.tables_info(id) ON DELETE CASCADE;


--
-- Name: table_players table_players_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.table_players
    ADD CONSTRAINT table_players_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE CASCADE;


--
-- Name: table_players table_players_table_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.table_players
    ADD CONSTRAINT table_players_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.tables_info(id) ON DELETE CASCADE;


--
-- Name: tables_info tables_info_tournament_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tables_info
    ADD CONSTRAINT tables_info_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON DELETE CASCADE;


--
-- Name: tournament_meta tournament_meta_tournament_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tournament_meta
    ADD CONSTRAINT tournament_meta_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON DELETE CASCADE;


--
-- Name: tournament_dm_dispatches tournament_dm_dispatches_tournament_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tournament_dm_dispatches
    ADD CONSTRAINT tournament_dm_dispatches_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON DELETE CASCADE;


--
-- Name: tournament_dm_dispatches tournament_dm_dispatches_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tournament_dm_dispatches
    ADD CONSTRAINT tournament_dm_dispatches_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


